# Generated by Django 5.2.8 on 2025-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('account_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('address', models.TextField(max_length=100)),
                ('mob_no', models.BigIntegerField()),
            ],
        ),
    ]
